package com.javaeplanet.jwt.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.javaeplanet.jwt.entity.User;
import com.javaeplanet.jwt.entity.UserRequest;
import com.javaeplanet.jwt.entity.UserResponse;
import com.javaeplanet.jwt.service.UserService;
import com.javaeplanet.jwt.util.JwtUtil;

@RestController
@RequestMapping("/api")
public class UserController {
	@Autowired
	private JwtUtil util;

	@Autowired
	private UserService service;

	@Autowired
	private AuthenticationManager authenticationManager;

	@PostMapping("/save")
	public ResponseEntity<String> saveUserDetails(@RequestBody User user) {
		Integer id = service.saveUser(user);
		return new ResponseEntity<String>("user'" + id + "'saved", HttpStatus.OK);
	}

	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest request) {
		authenticationManager
				.authenticate(new UsernamePasswordAuthenticationToken(request.getUsername(), request.getPassword()));
		String token = util.generateToken(request.getUsername());
		return ResponseEntity.ok(new UserResponse(token, "Success Generated by Javaeplanet "));
	}

	@PostMapping("/welcome")
	public ResponseEntity<String> accessData(Principal pal) {
		return ResponseEntity.ok("Hello user" + pal.getName());
	}
}
